export const VIGILANCE_TEXTS = {
    vert: [
        "Aucun danger météorologique n'est à signaler. Profitez de cette belle journée en toute sérénité.",
        "Le ciel est clair et les conditions sont idéales. Aucune vigilance particulière n'est requise.",
        "Temps calme sur l'ensemble de l'île. C'est le moment parfait pour des activités en extérieur.",
        "La météo est clémente aujourd'hui. Pas de perturbations prévues à l'horizon.",
        "Situation normale. L'alizé souffle doucement et aucun phénomène dangereux ne s'approche.",
        "Soleil prédominant avec quelques passages nuageux inoffensifs. Une journée typique et agréable.",
        "Les alizés ventilent agréablement l'île, dispersant les rares nuages. Mer belle à peu agitée.",
        "Conditions stables et ensoleillées. Idéal pour la plage ou la randonnée.",
        "Ciel bleu azur, quelques cumulus de beau temps sur les mornes. Risque de pluie quasi nul.",
        "Belle journée en perspective. Les températures sont de saison et le vent est faible.",
        "Le soleil brille généreusement du Nord au Sud. Profitez-en !",
        "Pas de vigilance en cours. La mer est calme et le vent modéré.",
        "Une météo tropicale classique : du soleil, de la chaleur et une légère brise.",
        "Le temps est au beau fixe. Visibilité excellente sur les sommets.",
        "Journée radiieuse sans nuage significatif. Indice UV élevé, pensez à vous protéger."
    ],
    jaune: [
        "Soyez attentifs si vous pratiquez des activités sensibles au risque météorologique. Des phénomènes habituels mais occasionnellement dangereux sont prévus.",
        "Vigilance Jaune : Prudence près des cours d'eau et sur le littoral. Tenez-vous au courant de l'évolution de la situation.",
        "Quelques perturbations sont possibles. Restez informés des bulletins météo si vous devez vous déplacer.",
        "Attention aux averses localement orageuses. Les sols peuvent être glissants et la visibilité réduite.",
        "Le temps se dégrade légèrement. Une vigilance est de mise pour les activités nautiques et de plein air.",
        "Passage d'une onde tropicale peu active. Des averses modérées peuvent survenir, accompagnées de quelques rafales.",
        "Mer agitée en Atlantique et canaux. Soyez prudents lors des sorties en mer.",
        "Risque d'orages isolés en fin de journée, particulièrement sur le relief.",
        "Vents soutenus de secteur Est, rendant la mer hachée. Baignade déconseillée sur la côte au vent.",
        "Des paquets de mer peuvent affecter les zones basses du littoral Nord-Atlantique.",
        "Atmosphère instable favorisant le développement de nuages porteurs d'averses soutenues.",
        "Les cumuls de pluie pourraient être significatifs localement. Soyez vigilants sur les routes.",
        "Risque de fortes chaleurs associées à une panne d'alizé. Hydratez-vous.",
        "Temps maussade avec des passages pluvieux fréquents. Visibilité réduite sous les grains.",
        "Une dégradation pluvio-orageuse aborde l'archipel. Prudence dans les zones inondables."
    ],
    orange: [
        "Soyez très vigilants, des phénomènes dangereux sont prévus. Tenez-vous au courant de l'évolution de la situation et suivez les conseils de sécurité émis par les pouvoirs publics.",
        "Vigilance Orange : Limitez vos déplacements et mettez-vous à l'abri. Conditions météorologiques difficiles attendues.",
        "Alerte Orange : Fortes pluies et risques d'inondations. Évitez les zones basses et les passages à gué.",
        "Situation dégradée : Des vents violents ou une mer très agitée sont annoncés. Sécurisez vos biens et restez prudents.",
        "Prudence absolue. Les conditions météo peuvent causer des accidents. Respectez strictement les consignes des autorités.",
        "Approche d'une onde tropicale active. Des cumuls de pluie importants sont attendus en peu de temps.",
        "Risque élevé d'inondations et de glissements de terrain. Évitez absolument le réseau secondaire.",
        "Mer forte à très forte. Houle cyclonique dangereuse déferlant sur les côtes exposées.",
        "Orages violents avec forte activité électrique. Débranchez les appareils sensibles.",
        "Vents tempétueux possibles sous les grains les plus forts. Attention aux chutes d'arbres.",
        "La rivière est en crue. Ne tentez jamais de traverser un gué submergé.",
        "Épisode de brume de sable intense réduisant fortement la visibilité et la qualité de l'air.",
        "Mer démontée. Les sorties en mer sont formellement interdites.",
        "Dégradation majeure rapide. Rejoignez votre domicile et limitez vos sorties au strict nécessaire.",
        "Les sols sont saturés. De nouveaux éboulements sont à craindre sur les routes de montagne."
    ],
    rouge: [
        "Une vigilance absolue s'impose. Des phénomènes dangereux d'intensité exceptionnelle sont prévus. Tenez-vous régulièrement au courant de la situation et respectez impérativement les consignes de sécurité.",
        "ALERTE ROUGE : Danger extrême. Restez confinés et n'entreprenez aucun déplacement.",
        "Situation critique. Des intempéries majeures impactent l'île. Suivez les instructions de la préfecture à la lettre.",
        "Danger de mort potentiel dû aux conditions météo. Protégez-vous et vos proches immédiatement.",
        "Vigilance Rouge activée. Tous les services de secours sont en alerte. Ne sortez sous aucun prétexte.",
        "Passage d'un cyclone à proximité immédiate. Vents destructeurs et pluies diluviennes attendus.",
        "Risque de submersion marine majeure. Évacuez les zones côtières si ordonné par les autorités.",
        "Inondations généralisées catastrophiques possibles. Réfugiez-vous en hauteur.",
        "Le réseau routier est impraticable. Restez chez vous en sécurité.",
        "Conditions d'ouragan. Protégez les ouvertures et consolidez votre abri.",
        "Coupures d'électricité et d'eau probables. Constituez des réserves d'urgence.",
        "La mer envahit les terres sur le littoral exposé. Danger extrême.",
        "Vents dépassant les 120 km/h en rafales. Ne restez pas près des fenêtres.",
        "Alerte Maximale. La situation est hors de contrôle. Attendez les secours ou la fin de l'épisode.",
        "Phénomène cyclonique majeur. La Martinique est en alerte rouge cyclone."
    ],
    violet: [
        "Vigilance Violette : Confinement strict obligatoire. Le cyclone est imminent ou en cours. Danger de mort immédiat.",
        "URGENCE ABSOLUE : L'œil du cyclone passe sur la Martinique. Restez barricadés jusqu'à la levée de l'alerte.",
        "Conditions cycloniques extrêmes. Ne sortez jamais, même si le temps semble se calmer (passage de l'œil).",
        "Alerte Violette. Protégez-vous dans la pièce la plus sûre de votre habitation. Éloignez-vous des ouvertures.",
        "Danger maximal. L'impact est en cours. Attendez les consignes officielles avant toute action.",
        "Passage du mur de l'œil. Vents cataclysmiques dévastant tout sur leur passage.",
        "Ne tentez aucune sortie, même pour sécuriser votre maison. Votre vie est en jeu.",
        "Confinement TOTAL. Les secours ne peuvent plus intervenir.",
        "Le cyclone frappe de plein fouet. Restez à l'abri, loin des baies vitrées.",
        "Vigilance Violette Cyclone. C'est la phase la plus critique. Courage et prudence.",
        "Isilement total requis. Préparez-vous à un impact violent et durable.",
        "Attention au calme trompeur de l'œil. Les vents reprendront violemment en sens inverse.",
        "Toutes les routes sont coupées. Restez où vous êtes.",
        "Risque d'effondrement des structures légères. Abritez-vous sous des tables solides si nécessaire.",
        "Situation de catastrophe naturelle majeure en cours."
    ],
    gris: [
        "Fin de l'épisode de vigilance. Restez tout de même prudents, les sols peuvent rester gorgés d'eau et les infrastructures fragilisées.",
        "Le danger s'éloigne. La vigilance est levée mais la prudence reste de mise lors de vos déplacements.",
        "Retour progressif à la normale. Vérifiez l'état des routes avant de circuler.",
        "L'alerte est terminée. Les services de l'État procèdent aux vérifications d'usage.",
        "Amélioration confirmée. Bon retour à vos activités habituelles.",
        "Vigilance levée. Attention aux chutes d'arbres ou câbles électriques résiduelles.",
        "Le temps se rétablit mais la mer reste agitée. Prudence sur le littoral.",
        "Épisode terminé. Nettoyez les abords de votre maison avec prudence.",
        "Les cours d'eau peuvent encore être en crue. Ne vous approchez pas des berges.",
        "Reprise progressive de l'activité. Restez informés des conditions de circulation.",
        "Le calme est revenu. Une pensée pour ceux touchés par les intempéries.",
        "Fin de la menace cyclonique. Déconfinement autorisé mais restez vigilants.",
        "Les écoles et administrations rouvriront selon les consignes préfectorales.",
        "L'onde tropicale s'est éloignée. Le soleil revient progressivement.",
        "Rétablissement progressif des réseaux (eau, électricité). Patience."
    ],
    erreur: [
        "Oups, quelque chose ne va pas... Impossible de récupérer les données de vigilance pour le moment.",
        "Erreur de connexion aux services météo. Nous réessayons de charger les informations.",
        "Données indisponibles. Veuillez vérifier votre connexion internet ou réessayer plus tard.",
        "Un problème technique empêche l'affichage de la vigilance. Nos équipes sont sur le coup.",
        "Météo Martinique ne répond pas. Veuillez consulter les médias officiels en attendant le rétablissement du service."
    ]
}
